glossary-server-api:
    image: freele/dockers:glossary
    ports:
        - "80:3000"
    links:
        - mongo:mongo

mongo:
    image: mongo
    command: mongod --smallfiles
    volumes:
        - /data/mongo:/data/db